# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hotel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'

  # Pods for hotel

  target 'hotelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hotelUITests' do
    # Pods for testing
  end

end
